- name: bertvv.dhcp
  src: bertvv.dhcp
- name: geerlingguy.ntp
  src: geerlingguy.ntp
- name: MichaelRigart.interfaces
  version: develop
  src: https://github.com/awlx/ansible-role-interfaces/archive/fix_bonding_and_vlans.tar.gz
- name: Stouts.openvpn
  version: develop
  src: https://github.com/awlx/Stouts.openvpn/archive/develop.tar.gz
- name: geerlingguy.pip
  src: geerlingguy.pip
- name: geerlingguy.docker
  src: geerlingguy.docker
- name: tenhishadow.salt_minion
  src: tenhishadow.salt_minion
