all:
    children:
        jumphost:
            hosts:
                guardian:
                    ansible_host: guardian.ffmuc.net
        new:
            hosts:
                new-machine:
                    ansible_host: 10.80.248.28
