all:
    children:
        jumphost:
            hosts:
                guardian:
                    ansible_host: guardian.ffmuc.net
        proxmox:
            hosts:
                proxmox.in.ffmuc.net:
                    ansible_host: proxmox.in.ffmuc.net
        new:
            hosts:
                new-machine:
                    ansible_host: 10.80.248.29
